name: english-tutor-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - python-dotenv
  - openai
  - pydub
  - gtts
  - ffmpeg
  - pip
  - pip:
      - gradio==5.29.0
      - gradio-client==1.10.0
